version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "axum"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "sha2"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "thiserror"
        update-types: ["version-update:semver-major"]
